server:
  port: 8080
  servlet:
    context-path: /sjk
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sjk?serverTimezone=Asia/Seoul
    username: sjk
    password: sjk1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #table create/update/none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Entity 생성시 변수이름 그대로 table 컬럼생성
      use-new-id-generator-mappings: false  #JPA 넘버링 전략 설정 true : Ok
    show-sql: true #console print
    properties:
      hibernate.format_sql: true #console printed sql 정렬

  jackson:
    serialization:
      fail-on-empty-beans: false

  devtools:
    restart:
      enabled: true
